// @ts-nocheck
// Generated by build-style — maps example name -> lazy component.
import * as React from "react"

export const examples: Record<string, React.LazyExoticComponent<React.ComponentType>> = {
  "accordion-basic": React.lazy(async () => {
    const m = await import("@/registry/examples/accordion-basic")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "accordion-borders": React.lazy(async () => {
    const m = await import("@/registry/examples/accordion-borders")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "accordion-card": React.lazy(async () => {
    const m = await import("@/registry/examples/accordion-card")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "accordion-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/accordion-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "accordion-disabled": React.lazy(async () => {
    const m = await import("@/registry/examples/accordion-disabled")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "accordion-multiple": React.lazy(async () => {
    const m = await import("@/registry/examples/accordion-multiple")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "alert-action": React.lazy(async () => {
    const m = await import("@/registry/examples/alert-action")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "alert-basic": React.lazy(async () => {
    const m = await import("@/registry/examples/alert-basic")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "alert-colors": React.lazy(async () => {
    const m = await import("@/registry/examples/alert-colors")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "alert-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/alert-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "alert-destructive": React.lazy(async () => {
    const m = await import("@/registry/examples/alert-destructive")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "alert-dialog-basic": React.lazy(async () => {
    const m = await import("@/registry/examples/alert-dialog-basic")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "alert-dialog-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/alert-dialog-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "alert-dialog-destructive": React.lazy(async () => {
    const m = await import("@/registry/examples/alert-dialog-destructive")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "alert-dialog-media": React.lazy(async () => {
    const m = await import("@/registry/examples/alert-dialog-media")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "alert-dialog-small-media": React.lazy(async () => {
    const m = await import("@/registry/examples/alert-dialog-small-media")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "alert-dialog-small": React.lazy(async () => {
    const m = await import("@/registry/examples/alert-dialog-small")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "aspect-ratio-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/aspect-ratio-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "aspect-ratio-portrait": React.lazy(async () => {
    const m = await import("@/registry/examples/aspect-ratio-portrait")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "aspect-ratio-square": React.lazy(async () => {
    const m = await import("@/registry/examples/aspect-ratio-square")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "attachment-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/attachment-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "attachment-group": React.lazy(async () => {
    const m = await import("@/registry/examples/attachment-group")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "attachment-image": React.lazy(async () => {
    const m = await import("@/registry/examples/attachment-image")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "attachment-sizes": React.lazy(async () => {
    const m = await import("@/registry/examples/attachment-sizes")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "attachment-states": React.lazy(async () => {
    const m = await import("@/registry/examples/attachment-states")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "attachment-trigger": React.lazy(async () => {
    const m = await import("@/registry/examples/attachment-trigger")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "avatar-badge-icon": React.lazy(async () => {
    const m = await import("@/registry/examples/avatar-badge-icon")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "avatar-badge": React.lazy(async () => {
    const m = await import("@/registry/examples/avatar-badge")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "avatar-basic": React.lazy(async () => {
    const m = await import("@/registry/examples/avatar-basic")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "avatar-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/avatar-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "avatar-dropdown": React.lazy(async () => {
    const m = await import("@/registry/examples/avatar-dropdown")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "avatar-group-count-icon": React.lazy(async () => {
    const m = await import("@/registry/examples/avatar-group-count-icon")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "avatar-group-count": React.lazy(async () => {
    const m = await import("@/registry/examples/avatar-group-count")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "avatar-group": React.lazy(async () => {
    const m = await import("@/registry/examples/avatar-group")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "avatar-size": React.lazy(async () => {
    const m = await import("@/registry/examples/avatar-size")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "badge-colors": React.lazy(async () => {
    const m = await import("@/registry/examples/badge-colors")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "badge-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/badge-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "badge-icon": React.lazy(async () => {
    const m = await import("@/registry/examples/badge-icon")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "badge-link": React.lazy(async () => {
    const m = await import("@/registry/examples/badge-link")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "badge-spinner": React.lazy(async () => {
    const m = await import("@/registry/examples/badge-spinner")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "badge-variants": React.lazy(async () => {
    const m = await import("@/registry/examples/badge-variants")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "breadcrumb-basic": React.lazy(async () => {
    const m = await import("@/registry/examples/breadcrumb-basic")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "breadcrumb-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/breadcrumb-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "breadcrumb-dropdown": React.lazy(async () => {
    const m = await import("@/registry/examples/breadcrumb-dropdown")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "breadcrumb-ellipsis": React.lazy(async () => {
    const m = await import("@/registry/examples/breadcrumb-ellipsis")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "breadcrumb-link": React.lazy(async () => {
    const m = await import("@/registry/examples/breadcrumb-link")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "breadcrumb-separator": React.lazy(async () => {
    const m = await import("@/registry/examples/breadcrumb-separator")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "bubble-alignment": React.lazy(async () => {
    const m = await import("@/registry/examples/bubble-alignment")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "bubble-collapsible": React.lazy(async () => {
    const m = await import("@/registry/examples/bubble-collapsible")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "bubble-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/bubble-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "bubble-group-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/bubble-group-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "bubble-popover": React.lazy(async () => {
    const m = await import("@/registry/examples/bubble-popover")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "bubble-tooltip": React.lazy(async () => {
    const m = await import("@/registry/examples/bubble-tooltip")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "button-default": React.lazy(async () => {
    const m = await import("@/registry/examples/button-default")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "button-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/button-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "button-destructive": React.lazy(async () => {
    const m = await import("@/registry/examples/button-destructive")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "button-ghost": React.lazy(async () => {
    const m = await import("@/registry/examples/button-ghost")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "button-group-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/button-group-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "button-group-dropdown": React.lazy(async () => {
    const m = await import("@/registry/examples/button-group-dropdown")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "button-group-input-group": React.lazy(async () => {
    const m = await import("@/registry/examples/button-group-input-group")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "button-group-input": React.lazy(async () => {
    const m = await import("@/registry/examples/button-group-input")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "button-group-nested": React.lazy(async () => {
    const m = await import("@/registry/examples/button-group-nested")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "button-group-orientation": React.lazy(async () => {
    const m = await import("@/registry/examples/button-group-orientation")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "button-group-popover": React.lazy(async () => {
    const m = await import("@/registry/examples/button-group-popover")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "button-group-select": React.lazy(async () => {
    const m = await import("@/registry/examples/button-group-select")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "button-group-separator": React.lazy(async () => {
    const m = await import("@/registry/examples/button-group-separator")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "button-group-size": React.lazy(async () => {
    const m = await import("@/registry/examples/button-group-size")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "button-icon": React.lazy(async () => {
    const m = await import("@/registry/examples/button-icon")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "button-link": React.lazy(async () => {
    const m = await import("@/registry/examples/button-link")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "button-outline": React.lazy(async () => {
    const m = await import("@/registry/examples/button-outline")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "button-render": React.lazy(async () => {
    const m = await import("@/registry/examples/button-render")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "button-rounded": React.lazy(async () => {
    const m = await import("@/registry/examples/button-rounded")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "button-secondary": React.lazy(async () => {
    const m = await import("@/registry/examples/button-secondary")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "button-size": React.lazy(async () => {
    const m = await import("@/registry/examples/button-size")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "button-spinner": React.lazy(async () => {
    const m = await import("@/registry/examples/button-spinner")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "calendar-basic": React.lazy(async () => {
    const m = await import("@/registry/examples/calendar-basic")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "calendar-booked-dates": React.lazy(async () => {
    const m = await import("@/registry/examples/calendar-booked-dates")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "calendar-caption": React.lazy(async () => {
    const m = await import("@/registry/examples/calendar-caption")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "calendar-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/calendar-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "calendar-multiple": React.lazy(async () => {
    const m = await import("@/registry/examples/calendar-multiple")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "calendar-time": React.lazy(async () => {
    const m = await import("@/registry/examples/calendar-time")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "calendar-week-numbers": React.lazy(async () => {
    const m = await import("@/registry/examples/calendar-week-numbers")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "card-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/card-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "card-edge-to-edge": React.lazy(async () => {
    const m = await import("@/registry/examples/card-edge-to-edge")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "card-image": React.lazy(async () => {
    const m = await import("@/registry/examples/card-image")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "card-small": React.lazy(async () => {
    const m = await import("@/registry/examples/card-small")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "card-spacing": React.lazy(async () => {
    const m = await import("@/registry/examples/card-spacing")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "carousel-api": React.lazy(async () => {
    const m = await import("@/registry/examples/carousel-api")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "carousel-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/carousel-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "carousel-multiple": React.lazy(async () => {
    const m = await import("@/registry/examples/carousel-multiple")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "carousel-orientation": React.lazy(async () => {
    const m = await import("@/registry/examples/carousel-orientation")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "carousel-size": React.lazy(async () => {
    const m = await import("@/registry/examples/carousel-size")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "carousel-spacing": React.lazy(async () => {
    const m = await import("@/registry/examples/carousel-spacing")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "chart-tooltip": React.lazy(async () => {
    const m = await import("@/registry/examples/chart-tooltip")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "checkbox-basic": React.lazy(async () => {
    const m = await import("@/registry/examples/checkbox-basic")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "checkbox-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/checkbox-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "checkbox-description": React.lazy(async () => {
    const m = await import("@/registry/examples/checkbox-description")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "checkbox-disabled": React.lazy(async () => {
    const m = await import("@/registry/examples/checkbox-disabled")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "checkbox-group": React.lazy(async () => {
    const m = await import("@/registry/examples/checkbox-group")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "checkbox-invalid": React.lazy(async () => {
    const m = await import("@/registry/examples/checkbox-invalid")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "checkbox-table": React.lazy(async () => {
    const m = await import("@/registry/examples/checkbox-table")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "collapsible-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/collapsible-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "collapsible-file-tree": React.lazy(async () => {
    const m = await import("@/registry/examples/collapsible-file-tree")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "collapsible-settings": React.lazy(async () => {
    const m = await import("@/registry/examples/collapsible-settings")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "combobox-auto-highlight": React.lazy(async () => {
    const m = await import("@/registry/examples/combobox-auto-highlight")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "combobox-basic": React.lazy(async () => {
    const m = await import("@/registry/examples/combobox-basic")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "combobox-clear": React.lazy(async () => {
    const m = await import("@/registry/examples/combobox-clear")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "combobox-custom": React.lazy(async () => {
    const m = await import("@/registry/examples/combobox-custom")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "combobox-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/combobox-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "combobox-disabled": React.lazy(async () => {
    const m = await import("@/registry/examples/combobox-disabled")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "combobox-groups": React.lazy(async () => {
    const m = await import("@/registry/examples/combobox-groups")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "combobox-input-group": React.lazy(async () => {
    const m = await import("@/registry/examples/combobox-input-group")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "combobox-invalid": React.lazy(async () => {
    const m = await import("@/registry/examples/combobox-invalid")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "combobox-multiple": React.lazy(async () => {
    const m = await import("@/registry/examples/combobox-multiple")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "combobox-popup": React.lazy(async () => {
    const m = await import("@/registry/examples/combobox-popup")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "command-basic": React.lazy(async () => {
    const m = await import("@/registry/examples/command-basic")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "command-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/command-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "command-dialog": React.lazy(async () => {
    const m = await import("@/registry/examples/command-dialog")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "command-groups": React.lazy(async () => {
    const m = await import("@/registry/examples/command-groups")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "command-scrollable": React.lazy(async () => {
    const m = await import("@/registry/examples/command-scrollable")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "command-shortcuts": React.lazy(async () => {
    const m = await import("@/registry/examples/command-shortcuts")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "context-menu-basic": React.lazy(async () => {
    const m = await import("@/registry/examples/context-menu-basic")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "context-menu-checkboxes": React.lazy(async () => {
    const m = await import("@/registry/examples/context-menu-checkboxes")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "context-menu-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/context-menu-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "context-menu-destructive": React.lazy(async () => {
    const m = await import("@/registry/examples/context-menu-destructive")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "context-menu-groups": React.lazy(async () => {
    const m = await import("@/registry/examples/context-menu-groups")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "context-menu-icons": React.lazy(async () => {
    const m = await import("@/registry/examples/context-menu-icons")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "context-menu-radio": React.lazy(async () => {
    const m = await import("@/registry/examples/context-menu-radio")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "context-menu-shortcuts": React.lazy(async () => {
    const m = await import("@/registry/examples/context-menu-shortcuts")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "context-menu-sides": React.lazy(async () => {
    const m = await import("@/registry/examples/context-menu-sides")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "context-menu-submenu": React.lazy(async () => {
    const m = await import("@/registry/examples/context-menu-submenu")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "date-picker-dob": React.lazy(async () => {
    const m = await import("@/registry/examples/date-picker-dob")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "date-picker-input": React.lazy(async () => {
    const m = await import("@/registry/examples/date-picker-input")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "dialog-close-button": React.lazy(async () => {
    const m = await import("@/registry/examples/dialog-close-button")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "dialog-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/dialog-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "dialog-no-close-button": React.lazy(async () => {
    const m = await import("@/registry/examples/dialog-no-close-button")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "dialog-scrollable-content": React.lazy(async () => {
    const m = await import("@/registry/examples/dialog-scrollable-content")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "dialog-sticky-footer": React.lazy(async () => {
    const m = await import("@/registry/examples/dialog-sticky-footer")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "drawer-nested": React.lazy(async () => {
    const m = await import("@/registry/examples/drawer-nested")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "drawer-non-modal": React.lazy(async () => {
    const m = await import("@/registry/examples/drawer-non-modal")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "drawer-sides": React.lazy(async () => {
    const m = await import("@/registry/examples/drawer-sides")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "drawer-snap-points": React.lazy(async () => {
    const m = await import("@/registry/examples/drawer-snap-points")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "drawer-swipe-handle": React.lazy(async () => {
    const m = await import("@/registry/examples/drawer-swipe-handle")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "dropdown-menu-avatar": React.lazy(async () => {
    const m = await import("@/registry/examples/dropdown-menu-avatar")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "dropdown-menu-basic": React.lazy(async () => {
    const m = await import("@/registry/examples/dropdown-menu-basic")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "dropdown-menu-checkboxes-icons": React.lazy(async () => {
    const m = await import("@/registry/examples/dropdown-menu-checkboxes-icons")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "dropdown-menu-checkboxes": React.lazy(async () => {
    const m = await import("@/registry/examples/dropdown-menu-checkboxes")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "dropdown-menu-complex": React.lazy(async () => {
    const m = await import("@/registry/examples/dropdown-menu-complex")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "dropdown-menu-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/dropdown-menu-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "dropdown-menu-destructive": React.lazy(async () => {
    const m = await import("@/registry/examples/dropdown-menu-destructive")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "dropdown-menu-icons": React.lazy(async () => {
    const m = await import("@/registry/examples/dropdown-menu-icons")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "dropdown-menu-radio-group": React.lazy(async () => {
    const m = await import("@/registry/examples/dropdown-menu-radio-group")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "dropdown-menu-radio-icons": React.lazy(async () => {
    const m = await import("@/registry/examples/dropdown-menu-radio-icons")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "dropdown-menu-shortcuts": React.lazy(async () => {
    const m = await import("@/registry/examples/dropdown-menu-shortcuts")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "dropdown-menu-submenu": React.lazy(async () => {
    const m = await import("@/registry/examples/dropdown-menu-submenu")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "empty-avatar-group": React.lazy(async () => {
    const m = await import("@/registry/examples/empty-avatar-group")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "empty-avatar": React.lazy(async () => {
    const m = await import("@/registry/examples/empty-avatar")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "empty-card": React.lazy(async () => {
    const m = await import("@/registry/examples/empty-card")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "empty-input-group": React.lazy(async () => {
    const m = await import("@/registry/examples/empty-input-group")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "field-checkbox": React.lazy(async () => {
    const m = await import("@/registry/examples/field-checkbox")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "field-choice-card": React.lazy(async () => {
    const m = await import("@/registry/examples/field-choice-card")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "field-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/field-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "field-fieldset": React.lazy(async () => {
    const m = await import("@/registry/examples/field-fieldset")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "field-group": React.lazy(async () => {
    const m = await import("@/registry/examples/field-group")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "field-input": React.lazy(async () => {
    const m = await import("@/registry/examples/field-input")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "field-radio": React.lazy(async () => {
    const m = await import("@/registry/examples/field-radio")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "field-responsive": React.lazy(async () => {
    const m = await import("@/registry/examples/field-responsive")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "field-select": React.lazy(async () => {
    const m = await import("@/registry/examples/field-select")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "field-slider": React.lazy(async () => {
    const m = await import("@/registry/examples/field-slider")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "field-switch": React.lazy(async () => {
    const m = await import("@/registry/examples/field-switch")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "field-textarea": React.lazy(async () => {
    const m = await import("@/registry/examples/field-textarea")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "file-upload-list": React.lazy(async () => {
    const m = await import("@/registry/examples/file-upload-list")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "hover-card-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/hover-card-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "hover-card-sides": React.lazy(async () => {
    const m = await import("@/registry/examples/hover-card-sides")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-badge": React.lazy(async () => {
    const m = await import("@/registry/examples/input-badge")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-basic": React.lazy(async () => {
    const m = await import("@/registry/examples/input-basic")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-button-group": React.lazy(async () => {
    const m = await import("@/registry/examples/input-button-group")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/input-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-disabled": React.lazy(async () => {
    const m = await import("@/registry/examples/input-disabled")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-field": React.lazy(async () => {
    const m = await import("@/registry/examples/input-field")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-fieldgroup": React.lazy(async () => {
    const m = await import("@/registry/examples/input-fieldgroup")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-file": React.lazy(async () => {
    const m = await import("@/registry/examples/input-file")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-form": React.lazy(async () => {
    const m = await import("@/registry/examples/input-form")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-grid": React.lazy(async () => {
    const m = await import("@/registry/examples/input-grid")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-group-basic": React.lazy(async () => {
    const m = await import("@/registry/examples/input-group-basic")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-group-block-end": React.lazy(async () => {
    const m = await import("@/registry/examples/input-group-block-end")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-group-block-start": React.lazy(async () => {
    const m = await import("@/registry/examples/input-group-block-start")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-group-button-group": React.lazy(async () => {
    const m = await import("@/registry/examples/input-group-button-group")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-group-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/input-group-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-group-dropdown": React.lazy(async () => {
    const m = await import("@/registry/examples/input-group-dropdown")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-group-icon": React.lazy(async () => {
    const m = await import("@/registry/examples/input-group-icon")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-group-in-card": React.lazy(async () => {
    const m = await import("@/registry/examples/input-group-in-card")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-group-inline-end": React.lazy(async () => {
    const m = await import("@/registry/examples/input-group-inline-end")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-group-inline-start": React.lazy(async () => {
    const m = await import("@/registry/examples/input-group-inline-start")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-group-kbd": React.lazy(async () => {
    const m = await import("@/registry/examples/input-group-kbd")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-group-label": React.lazy(async () => {
    const m = await import("@/registry/examples/input-group-label")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-group-spinner": React.lazy(async () => {
    const m = await import("@/registry/examples/input-group-spinner")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-group-text": React.lazy(async () => {
    const m = await import("@/registry/examples/input-group-text")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-group-textarea-examples": React.lazy(async () => {
    const m = await import("@/registry/examples/input-group-textarea-examples")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-group-tooltip": React.lazy(async () => {
    const m = await import("@/registry/examples/input-group-tooltip")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-group-with-buttons": React.lazy(async () => {
    const m = await import("@/registry/examples/input-group-with-buttons")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-group-with-kbd": React.lazy(async () => {
    const m = await import("@/registry/examples/input-group-with-kbd")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-inline": React.lazy(async () => {
    const m = await import("@/registry/examples/input-inline")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-input-group": React.lazy(async () => {
    const m = await import("@/registry/examples/input-input-group")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-invalid": React.lazy(async () => {
    const m = await import("@/registry/examples/input-invalid")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-otp-controlled": React.lazy(async () => {
    const m = await import("@/registry/examples/input-otp-controlled")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-otp-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/input-otp-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-otp-disabled": React.lazy(async () => {
    const m = await import("@/registry/examples/input-otp-disabled")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-otp-form": React.lazy(async () => {
    const m = await import("@/registry/examples/input-otp-form")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-otp-invalid": React.lazy(async () => {
    const m = await import("@/registry/examples/input-otp-invalid")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-otp-separator": React.lazy(async () => {
    const m = await import("@/registry/examples/input-otp-separator")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "input-required": React.lazy(async () => {
    const m = await import("@/registry/examples/input-required")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "item-avatar": React.lazy(async () => {
    const m = await import("@/registry/examples/item-avatar")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "item-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/item-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "item-dropdown": React.lazy(async () => {
    const m = await import("@/registry/examples/item-dropdown")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "item-group": React.lazy(async () => {
    const m = await import("@/registry/examples/item-group")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "item-header": React.lazy(async () => {
    const m = await import("@/registry/examples/item-header")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "item-icon": React.lazy(async () => {
    const m = await import("@/registry/examples/item-icon")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "item-image": React.lazy(async () => {
    const m = await import("@/registry/examples/item-image")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "item-link": React.lazy(async () => {
    const m = await import("@/registry/examples/item-link")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "item-size": React.lazy(async () => {
    const m = await import("@/registry/examples/item-size")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "item-variant": React.lazy(async () => {
    const m = await import("@/registry/examples/item-variant")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "kbd-button": React.lazy(async () => {
    const m = await import("@/registry/examples/kbd-button")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "kbd-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/kbd-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "kbd-group": React.lazy(async () => {
    const m = await import("@/registry/examples/kbd-group")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "kbd-input-group": React.lazy(async () => {
    const m = await import("@/registry/examples/kbd-input-group")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "kbd-tooltip": React.lazy(async () => {
    const m = await import("@/registry/examples/kbd-tooltip")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "label-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/label-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "marker-border": React.lazy(async () => {
    const m = await import("@/registry/examples/marker-border")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "marker-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/marker-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "marker-icon": React.lazy(async () => {
    const m = await import("@/registry/examples/marker-icon")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "marker-separator": React.lazy(async () => {
    const m = await import("@/registry/examples/marker-separator")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "marker-shimmer": React.lazy(async () => {
    const m = await import("@/registry/examples/marker-shimmer")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "marker-status": React.lazy(async () => {
    const m = await import("@/registry/examples/marker-status")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "marker-variants": React.lazy(async () => {
    const m = await import("@/registry/examples/marker-variants")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "menubar-checkbox": React.lazy(async () => {
    const m = await import("@/registry/examples/menubar-checkbox")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "menubar-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/menubar-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "menubar-icons": React.lazy(async () => {
    const m = await import("@/registry/examples/menubar-icons")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "menubar-radio": React.lazy(async () => {
    const m = await import("@/registry/examples/menubar-radio")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "menubar-submenu": React.lazy(async () => {
    const m = await import("@/registry/examples/menubar-submenu")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "message-actions": React.lazy(async () => {
    const m = await import("@/registry/examples/message-actions")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "message-attachment": React.lazy(async () => {
    const m = await import("@/registry/examples/message-attachment")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "message-avatar": React.lazy(async () => {
    const m = await import("@/registry/examples/message-avatar")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "message-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/message-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "message-group": React.lazy(async () => {
    const m = await import("@/registry/examples/message-group")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "message-header-footer": React.lazy(async () => {
    const m = await import("@/registry/examples/message-header-footer")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "message-scroller-group-chat": React.lazy(async () => {
    const m = await import("@/registry/examples/message-scroller-group-chat")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "message-scroller-opening-position": React.lazy(async () => {
    const m = await import("@/registry/examples/message-scroller-opening-position")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "message-scroller-state": React.lazy(async () => {
    const m = await import("@/registry/examples/message-scroller-state")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "muted-item-group": React.lazy(async () => {
    const m = await import("@/registry/examples/muted-item-group")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "native-select-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/native-select-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "native-select-disabled": React.lazy(async () => {
    const m = await import("@/registry/examples/native-select-disabled")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "native-select-groups": React.lazy(async () => {
    const m = await import("@/registry/examples/native-select-groups")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "native-select-invalid": React.lazy(async () => {
    const m = await import("@/registry/examples/native-select-invalid")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "navigation-menu-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/navigation-menu-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "outline-item-group": React.lazy(async () => {
    const m = await import("@/registry/examples/outline-item-group")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "pagination-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/pagination-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "pagination-icons-only": React.lazy(async () => {
    const m = await import("@/registry/examples/pagination-icons-only")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "pagination-simple": React.lazy(async () => {
    const m = await import("@/registry/examples/pagination-simple")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "popover-alignments": React.lazy(async () => {
    const m = await import("@/registry/examples/popover-alignments")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "popover-basic": React.lazy(async () => {
    const m = await import("@/registry/examples/popover-basic")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "popover-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/popover-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "popover-form": React.lazy(async () => {
    const m = await import("@/registry/examples/popover-form")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "progress-controlled": React.lazy(async () => {
    const m = await import("@/registry/examples/progress-controlled")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "progress-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/progress-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "progress-label": React.lazy(async () => {
    const m = await import("@/registry/examples/progress-label")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "radio-fields": React.lazy(async () => {
    const m = await import("@/registry/examples/radio-fields")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "radio-group-choice-card": React.lazy(async () => {
    const m = await import("@/registry/examples/radio-group-choice-card")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "radio-group-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/radio-group-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "radio-group-description": React.lazy(async () => {
    const m = await import("@/registry/examples/radio-group-description")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "radio-group-disabled": React.lazy(async () => {
    const m = await import("@/registry/examples/radio-group-disabled")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "radio-group-fieldset": React.lazy(async () => {
    const m = await import("@/registry/examples/radio-group-fieldset")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "radio-group-invalid": React.lazy(async () => {
    const m = await import("@/registry/examples/radio-group-invalid")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "resizable-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/resizable-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "resizable-handle": React.lazy(async () => {
    const m = await import("@/registry/examples/resizable-handle")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "resizable-vertical": React.lazy(async () => {
    const m = await import("@/registry/examples/resizable-vertical")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "scroll-area-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/scroll-area-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "scroll-area-horizontal-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/scroll-area-horizontal-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "scroll-fade-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/scroll-fade-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "scroll-fade-edge": React.lazy(async () => {
    const m = await import("@/registry/examples/scroll-fade-edge")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "scroll-fade-horizontal": React.lazy(async () => {
    const m = await import("@/registry/examples/scroll-fade-horizontal")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "scroll-fade-none": React.lazy(async () => {
    const m = await import("@/registry/examples/scroll-fade-none")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "scroll-fade-overflow": React.lazy(async () => {
    const m = await import("@/registry/examples/scroll-fade-overflow")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "scroll-fade-size": React.lazy(async () => {
    const m = await import("@/registry/examples/scroll-fade-size")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "select-align-item": React.lazy(async () => {
    const m = await import("@/registry/examples/select-align-item")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "select-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/select-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "select-disabled": React.lazy(async () => {
    const m = await import("@/registry/examples/select-disabled")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "select-groups": React.lazy(async () => {
    const m = await import("@/registry/examples/select-groups")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "select-invalid": React.lazy(async () => {
    const m = await import("@/registry/examples/select-invalid")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "select-scrollable": React.lazy(async () => {
    const m = await import("@/registry/examples/select-scrollable")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "separator-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/separator-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "separator-list": React.lazy(async () => {
    const m = await import("@/registry/examples/separator-list")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "separator-menu": React.lazy(async () => {
    const m = await import("@/registry/examples/separator-menu")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "separator-vertical": React.lazy(async () => {
    const m = await import("@/registry/examples/separator-vertical")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "sheet-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/sheet-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "sheet-no-close-button": React.lazy(async () => {
    const m = await import("@/registry/examples/sheet-no-close-button")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "sheet-side": React.lazy(async () => {
    const m = await import("@/registry/examples/sheet-side")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "shimmer-angle": React.lazy(async () => {
    const m = await import("@/registry/examples/shimmer-angle")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "shimmer-color": React.lazy(async () => {
    const m = await import("@/registry/examples/shimmer-color")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "shimmer-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/shimmer-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "shimmer-duration": React.lazy(async () => {
    const m = await import("@/registry/examples/shimmer-duration")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "shimmer-marker": React.lazy(async () => {
    const m = await import("@/registry/examples/shimmer-marker")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "shimmer-none": React.lazy(async () => {
    const m = await import("@/registry/examples/shimmer-none")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "shimmer-once": React.lazy(async () => {
    const m = await import("@/registry/examples/shimmer-once")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "shimmer-rtl": React.lazy(async () => {
    const m = await import("@/registry/examples/shimmer-rtl")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "shimmer-spread": React.lazy(async () => {
    const m = await import("@/registry/examples/shimmer-spread")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "sidebar-controlled": React.lazy(async () => {
    const m = await import("@/registry/examples/sidebar-controlled")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "sidebar-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/sidebar-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "sidebar-footer": React.lazy(async () => {
    const m = await import("@/registry/examples/sidebar-footer")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "sidebar-group-collapsible": React.lazy(async () => {
    const m = await import("@/registry/examples/sidebar-group-collapsible")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "sidebar-group": React.lazy(async () => {
    const m = await import("@/registry/examples/sidebar-group")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "sidebar-header": React.lazy(async () => {
    const m = await import("@/registry/examples/sidebar-header")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "sidebar-menu-action": React.lazy(async () => {
    const m = await import("@/registry/examples/sidebar-menu-action")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "sidebar-menu-badge": React.lazy(async () => {
    const m = await import("@/registry/examples/sidebar-menu-badge")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "sidebar-menu-collapsible": React.lazy(async () => {
    const m = await import("@/registry/examples/sidebar-menu-collapsible")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "sidebar-menu-sub": React.lazy(async () => {
    const m = await import("@/registry/examples/sidebar-menu-sub")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "sidebar-menu": React.lazy(async () => {
    const m = await import("@/registry/examples/sidebar-menu")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "sidebar-rsc": React.lazy(async () => {
    const m = await import("@/registry/examples/sidebar-rsc")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "skeleton-avatar": React.lazy(async () => {
    const m = await import("@/registry/examples/skeleton-avatar")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "skeleton-card": React.lazy(async () => {
    const m = await import("@/registry/examples/skeleton-card")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "skeleton-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/skeleton-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "skeleton-form": React.lazy(async () => {
    const m = await import("@/registry/examples/skeleton-form")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "skeleton-table": React.lazy(async () => {
    const m = await import("@/registry/examples/skeleton-table")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "skeleton-text": React.lazy(async () => {
    const m = await import("@/registry/examples/skeleton-text")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "slider-controlled": React.lazy(async () => {
    const m = await import("@/registry/examples/slider-controlled")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "slider-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/slider-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "slider-disabled": React.lazy(async () => {
    const m = await import("@/registry/examples/slider-disabled")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "slider-multiple": React.lazy(async () => {
    const m = await import("@/registry/examples/slider-multiple")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "slider-range": React.lazy(async () => {
    const m = await import("@/registry/examples/slider-range")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "slider-vertical": React.lazy(async () => {
    const m = await import("@/registry/examples/slider-vertical")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "spinner-badge": React.lazy(async () => {
    const m = await import("@/registry/examples/spinner-badge")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "spinner-button": React.lazy(async () => {
    const m = await import("@/registry/examples/spinner-button")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "spinner-custom": React.lazy(async () => {
    const m = await import("@/registry/examples/spinner-custom")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "spinner-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/spinner-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "spinner-empty": React.lazy(async () => {
    const m = await import("@/registry/examples/spinner-empty")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "spinner-input-group": React.lazy(async () => {
    const m = await import("@/registry/examples/spinner-input-group")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "spinner-size": React.lazy(async () => {
    const m = await import("@/registry/examples/spinner-size")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "switch-choice-card": React.lazy(async () => {
    const m = await import("@/registry/examples/switch-choice-card")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "switch-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/switch-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "switch-description": React.lazy(async () => {
    const m = await import("@/registry/examples/switch-description")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "switch-disabled": React.lazy(async () => {
    const m = await import("@/registry/examples/switch-disabled")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "switch-invalid": React.lazy(async () => {
    const m = await import("@/registry/examples/switch-invalid")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "switch-sizes": React.lazy(async () => {
    const m = await import("@/registry/examples/switch-sizes")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "table-actions": React.lazy(async () => {
    const m = await import("@/registry/examples/table-actions")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "table-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/table-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "table-footer": React.lazy(async () => {
    const m = await import("@/registry/examples/table-footer")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "tabs-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/tabs-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "tabs-disabled": React.lazy(async () => {
    const m = await import("@/registry/examples/tabs-disabled")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "tabs-icons": React.lazy(async () => {
    const m = await import("@/registry/examples/tabs-icons")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "tabs-line": React.lazy(async () => {
    const m = await import("@/registry/examples/tabs-line")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "tabs-vertical": React.lazy(async () => {
    const m = await import("@/registry/examples/tabs-vertical")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "textarea-button": React.lazy(async () => {
    const m = await import("@/registry/examples/textarea-button")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "textarea-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/textarea-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "textarea-disabled": React.lazy(async () => {
    const m = await import("@/registry/examples/textarea-disabled")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "textarea-field": React.lazy(async () => {
    const m = await import("@/registry/examples/textarea-field")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "textarea-invalid": React.lazy(async () => {
    const m = await import("@/registry/examples/textarea-invalid")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "toast-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/toast-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "toast-promise": React.lazy(async () => {
    const m = await import("@/registry/examples/toast-promise")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "toast-types": React.lazy(async () => {
    const m = await import("@/registry/examples/toast-types")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "toggle-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/toggle-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "toggle-disabled": React.lazy(async () => {
    const m = await import("@/registry/examples/toggle-disabled")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "toggle-group-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/toggle-group-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "toggle-group-disabled": React.lazy(async () => {
    const m = await import("@/registry/examples/toggle-group-disabled")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "toggle-group-font-weight-selector": React.lazy(async () => {
    const m = await import("@/registry/examples/toggle-group-font-weight-selector")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "toggle-group-outline": React.lazy(async () => {
    const m = await import("@/registry/examples/toggle-group-outline")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "toggle-group-sizes": React.lazy(async () => {
    const m = await import("@/registry/examples/toggle-group-sizes")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "toggle-group-spacing": React.lazy(async () => {
    const m = await import("@/registry/examples/toggle-group-spacing")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "toggle-group-vertical": React.lazy(async () => {
    const m = await import("@/registry/examples/toggle-group-vertical")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "toggle-outline": React.lazy(async () => {
    const m = await import("@/registry/examples/toggle-outline")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "toggle-sizes": React.lazy(async () => {
    const m = await import("@/registry/examples/toggle-sizes")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "toggle-text": React.lazy(async () => {
    const m = await import("@/registry/examples/toggle-text")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "tooltip-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/tooltip-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "tooltip-disabled": React.lazy(async () => {
    const m = await import("@/registry/examples/tooltip-disabled")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "tooltip-keyboard": React.lazy(async () => {
    const m = await import("@/registry/examples/tooltip-keyboard")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "tooltip-sides": React.lazy(async () => {
    const m = await import("@/registry/examples/tooltip-sides")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "typography-blockquote": React.lazy(async () => {
    const m = await import("@/registry/examples/typography-blockquote")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "typography-demo": React.lazy(async () => {
    const m = await import("@/registry/examples/typography-demo")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "typography-h1": React.lazy(async () => {
    const m = await import("@/registry/examples/typography-h1")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "typography-h2": React.lazy(async () => {
    const m = await import("@/registry/examples/typography-h2")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "typography-h3": React.lazy(async () => {
    const m = await import("@/registry/examples/typography-h3")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "typography-h4": React.lazy(async () => {
    const m = await import("@/registry/examples/typography-h4")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "typography-inline-code": React.lazy(async () => {
    const m = await import("@/registry/examples/typography-inline-code")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "typography-large": React.lazy(async () => {
    const m = await import("@/registry/examples/typography-large")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "typography-lead": React.lazy(async () => {
    const m = await import("@/registry/examples/typography-lead")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "typography-list": React.lazy(async () => {
    const m = await import("@/registry/examples/typography-list")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "typography-muted": React.lazy(async () => {
    const m = await import("@/registry/examples/typography-muted")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "typography-p": React.lazy(async () => {
    const m = await import("@/registry/examples/typography-p")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "typography-small": React.lazy(async () => {
    const m = await import("@/registry/examples/typography-small")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
  "typography-table": React.lazy(async () => {
    const m = await import("@/registry/examples/typography-table")
    return { default: m.default ?? Object.values(m).find((v) => typeof v === "function") }
  }),
}
